-- MySQL Script generated by MySQL Workbench
-- Matheus Dias de Queiroz
-- Matricula: 5213

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE database IF NOT EXISTS `mydb`;

USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- (idFuncionario,cargo,nome,sexo,cpf,identidade,UFidentidad,eorgaoExpedidor,endereço,DataNascimento,
-- mae,pai,cidade,nacionalidade,nrTituloEleitor,zonaTituloEleitor,sessaoTituloEleitor,localTituloEleitor,
-- cidadeNascimento)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `idFuncionario` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NULL,
  `sexo` enum('M','F') NULL,
  `cpf` DECIMAL(9,0) NULL,
  `identidade` varchar(11) NULL,
  `UFidentidade` enum('AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO') NULL,
  `orgaoExpedidor` enum('SSP','CARTORIO CIVIL','POLICIA FEDERAL','DETRAN') NULL,
  `endereço` VARCHAR(30) NULL,
  `DataNascimento` DATE NULL,
  `mae` VARCHAR(30)NULL,
  `pai` varchar(30) NULL,
  `cidade` VARCHAR(45)NULL,
  `nacionalidade` VARCHAR(45)null default 'Brasilero(a)',
  `nrTituloEleitor` DECIMAL(12,0)NULL,
  `zonaTituloEleitor` decimal(3,0)NULL,
  `sessaoTituloEleitor` decimal(3,0)NULL,
  `localTituloEleitor` VARCHAR(45)NULL,
  `cidadeNascimento` VARCHAR(45)NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dependente` (
  `funcionario_idFuncionario` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NULL,
  `nascimento` DATE NULL,
  `sexo` enum('M','F') NULL,
  `cpf` DECIMAL(9,0) NULL,
  `identidade` VARCHAR(10) NULL,
  INDEX `fk_dependente_funcionario1_idx` (`funcionario_idFuncionario` ASC),
  PRIMARY KEY (`funcionario_idFuncionario`),
  CONSTRAINT `fk_dependente_funcionario1`
    FOREIGN KEY (`funcionario_idFuncionario`)
    REFERENCES `mydb`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instituto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instituto` (
  `idInstituto` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idInstituto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `idCurso` INT NOT NULL,
  `Instituto_idInstituto` INT NOT NULL,
  `nome_curso` VARCHAR(45) NULL,
  PRIMARY KEY (`idCurso`, `Instituto_idInstituto`),
  INDEX `fk_curso_Instituto1_idx` (`Instituto_idInstituto` ASC) ,
  CONSTRAINT `fk_curso_Instituto1`
    FOREIGN KEY (`Instituto_idInstituto`)
    REFERENCES `mydb`.`Instituto` (`idInstituto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `matricula` INT NOT NULL auto_increment,
  `curso_idCurso` INT NOT NULL,
  `nomeAluno` VARCHAR(45) NULL,
  `anoInicio` date NULL,
  `sexo` ENUM('M','F') NULL,
  `enderecoLocal` VARCHAR(45) NULL,
  `enderecoResponsavel` VARCHAR(45) NULL,
  `telefone` DECIMAL(11,0) NULL,
  `cpf` VARCHAR(45) NULL,
  `identidade` VARCHAR(45) NULL,
  `orgExpedidor` VARCHAR(5) NULL,
  `ufIdentidade` VARCHAR(2) NULL,
  `anoConclusaoEnsMed` YEAR(4) NULL,
  `escola2oGrau` VARCHAR(45) NULL,
  `pai` VARCHAR(45) NULL,
  `mae` VARCHAR(45) NULL,
  `dataNascimento` DATE NULL,
  `cidadeNascimento` VARCHAR(45) NULL,
  `nacionalidade` VARCHAR(45) DEFAULT 'Brasil' NULL,
  `pais` VARCHAR(45) NULL,
  `nrTituloEleitor` VARCHAR(45) NULL,
  `zonaTituloEleitor` INT NULL,
  `localTituloEleitor` VARCHAR(45) NULL,
  `sesaoTituloEleitor` INT NULL,
  `ufTituloEleitor` VARCHAR(2) NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_aluno_curso1_idx` (`curso_idCurso` ASC) ,
  CONSTRAINT `fk_aluno_curso1`
    FOREIGN KEY (`curso_idCurso`)
    REFERENCES `mydb`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`periodo` (
  `idPeriodo` INT NOT NULL,
  `curso_idCurso` INT NOT NULL,
  `disciplina_idDisciplina` INT NOT NULL,
  `anoPeriodo` YEAR(4) NULL,
  INDEX `fk_periodo_curso1_idx` (`curso_idCurso` ASC),
  PRIMARY KEY (`idPeriodo`),
  CONSTRAINT `fk_periodo_disciplina1`
    FOREIGN KEY (`disciplina_idDisciplina`)
    REFERENCES `mydb`.`disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_periodo_curso1`
    FOREIGN KEY (`curso_idCurso`)
    REFERENCES `mydb`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargo` (
  `idCargo` INT NOT NULL,
  `cargo_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idCargo`)
  )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina` (
  `idDisciplina` INT NOT NULL,
  `funcionario_idFuncionario` INT NOT NULL,
  `aluno_matricula` INT NOT NULL,
  `aluno_curso_idCurso` INT NOT NULL,
  `nome_discipilina` VARCHAR(20) NULL,
  `creditos` DECIMAL(1,0) NULL,
  `carga_hora_teorica` TIME NULL,
  `carga_hora_pratica` TIME NULL,
  `semestreOfertado` ENUM('1','2') NULL,
  PRIMARY KEY (`idDisciplina`),
  INDEX `fk_disciplina_funcionario1_idx` (`funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_disciplina_funcionario1`
    FOREIGN KEY (`funcionario_idFuncionario`)
    REFERENCES `mydb`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  INDEX `fk_disciplina_aluno1_idx` (`aluno_matricula` ASC),
  INDEX `fk_disciplina_aluno2_idx` (`aluno_curso_idCurso` ASC),
  CONSTRAINT `fk_disciplina_aluno1`
    FOREIGN KEY (`aluno_matricula`)
    REFERENCES `mydb`.`aluno` (`matricula`),
    FOREIGN KEY (`aluno_curso_idCurso`)
    REFERENCES `mydb`.`aluno` (`curso_idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina_has_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina_has_curso` (
  `curso_idCurso` INT NOT NULL,
  `disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`curso_idCurso`, `disciplina_idDisciplina`),
  INDEX `fk_curso_has_disciplina_disciplina1_idx` (`disciplina_idDisciplina` ASC),
  INDEX `fk_curso_has_disciplina_curso1_idx` (`curso_idCurso` ASC),
  CONSTRAINT `fk_curso_has_disciplina_curso1`
    FOREIGN KEY (`curso_idCurso`)
    REFERENCES `mydb`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_has_disciplina_disciplina1`
    FOREIGN KEY (`disciplina_idDisciplina`)
    REFERENCES `mydb`.`disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma` (
  `periodo_disciplina_idDisciplina` INT NOT NULL,
  `periodo_curso_idCurso` INT NOT NULL,
  `disciplina_idDisciplina` INT NOT NULL,
  `nrSala` VARCHAR(10) NULL,
  `dia` DATE NULL,
  `hora` TIME NULL,
  INDEX `fk_turma_periodo1_idx` (`periodo_disciplina_idDisciplina` ASC),
  INDEX `fk_turma_periodo2_idx` (`periodo_curso_idCurso` ASC),
  PRIMARY KEY (`disciplina_idDisciplina`, `periodo_curso_idCurso`, `periodo_disciplina_idDisciplina`),
  CONSTRAINT `fk_turma_disciplina1`
    FOREIGN KEY (`disciplina_idDisciplina`)
    REFERENCES `mydb`.`disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_periodo1`
    FOREIGN KEY (`periodo_disciplina_idDisciplina`)
    REFERENCES `mydb`.`periodo` (`disciplina_idDisciplina`),
    FOREIGN KEY (`periodo_curso_idCurso`)
    REFERENCES `mydb`.`periodo` (`curso_idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`prerequisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prerequisito` (
  `disciplina_idDisciplina` INT NOT NULL,
  `prerequisito` VARCHAR(20) NULL,
  PRIMARY KEY (`disciplina_idDisciplina`),
  CONSTRAINT `fk_prerequisito_disciplina1`
    FOREIGN KEY (`disciplina_idDisciplina`)
    REFERENCES `mydb`.`disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
