-- MySQL Script generated by MySQL Workbench
-- Fri Nov 23 10:47:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Instituto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instituto` (
  `idInstituto` INT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idInstituto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `idCurso` INT NULL,
  `Instituto_idInstituto` INT NOT NULL,
  `nome_curso` VARCHAR(45) NULL,
  PRIMARY KEY (`idCurso`, `Instituto_idInstituto`),
  INDEX `fk_curso_Instituto1_idx` (`Instituto_idInstituto` ASC),
  CONSTRAINT `fk_curso_Instituto1`
    FOREIGN KEY (`Instituto_idInstituto`)
    REFERENCES `mydb`.`Instituto` (`idInstituto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `matricula` INT NULL,
  `curso_idCurso` INT NOT NULL,
  `anoConclusaoEnsMed` YEAR(4) NULL,
  `escola2oGrau` VARCHAR(45) NULL,
  PRIMARY KEY (`matricula`, `curso_idCurso`),
  INDEX `fk_aluno_curso1_idx` (`curso_idCurso` ASC),
  CONSTRAINT `fk_aluno_curso1`
    FOREIGN KEY (`curso_idCurso`)
    REFERENCES `mydb`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `idFuncionario` INT NULL,
  `atua` ENUM('tecnico', 'professor') NULL,
  `funcionario_idFuncionario` INT NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registro` (
  `aluno_matricula` INT NULL,
  `funcionario_idFuncionario` INT NULL,
  `nome` VARCHAR(45) NULL,
  `sexo` ENUM('M', 'F') NULL,
  `cpf` DECIMAL(9,0) NULL,
  `identidade` VARCHAR(10) NULL,
  `UFidentidade` VARCHAR(2) NULL,
  `orgaoExpedidor` VARCHAR(5) NULL,
  `endereço` VARCHAR(45) NULL,
  `DataNascimento` DATE NULL,
  `mae` VARCHAR(45) NULL,
  `pai` INT NULL,
  `cidade` VARCHAR(45) NULL,
  `nacionalidade` VARCHAR(45) NULL,
  `nrTituloEleitor` INT NULL,
  `zonaTituloEleitor` INT NULL,
  `localTituloEleitor` VARCHAR(45) NULL,
  `cidadeNascimento` VARCHAR(45) NULL,
  `telefone` INT NULL,
  CONSTRAINT `fk_registro_aluno1`
    FOREIGN KEY (`aluno_matricula`)
    REFERENCES `mydb`.`aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_funcionario1`
    FOREIGN KEY (`funcionario_idFuncionario`)
    REFERENCES `mydb`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dependente` (
  `funcionario_idFuncionario` INT NULL,
  `funcionario_registro_aluno_matricula` INT NULL,
  `nome` VARCHAR(45) NULL,
  `nascimento` DATE NULL,
  `sexo` TINYINT NULL,
  `cpf` VARCHAR(9) NULL,
  `identidade` VARCHAR(10) NULL,
  CONSTRAINT `fk_dependente_funcionario1`
    FOREIGN KEY (`funcionario_idFuncionario`)
    REFERENCES `mydb`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina` (
  `idDisciplina` INT NULL,
  `aluno_matricula` INT NULL,
  `aluno_curso_idCurso` INT NULL,
  `nome_discipilina` VARCHAR(45) NULL,
  `creditos` INT NULL,
  `carga_hora_teorica` TIME NULL,
  `carga_hora_pratica` TIME NULL,
  `semestreOfertado` INT NULL,
  PRIMARY KEY (`idDisciplina`),
  INDEX `fk_disciplina_aluno1_idx` (`aluno_matricula` ASC, `aluno_curso_idCurso` ASC)  ,
  CONSTRAINT `fk_disciplina_aluno1`
    FOREIGN KEY (`aluno_matricula` , `aluno_curso_idCurso`)
    REFERENCES `mydb`.`aluno` (`matricula` , `curso_idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`periodo` (
  `idPeriodo` INT NULL,
  `curso_idCurso` INT NULL,
  `disciplina_idDisciplina` INT NULL,
  `anoPeriodo` YEAR(4) NULL,
  INDEX `fk_periodo_curso1_idx` (`curso_idCurso` ASC)  ,
  PRIMARY KEY (`idPeriodo`),
  CONSTRAINT `fk_periodo_disciplina1`
    FOREIGN KEY (`disciplina_idDisciplina`)
    REFERENCES `mydb`.`disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_periodo_curso1`
    FOREIGN KEY (`curso_idCurso`)
    REFERENCES `mydb`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma` (
    `disciplina_idDisciplina` INT NULL,
    `periodo_disciplina_idDisciplina` INT NULL,
    `periodo_curso_idCurso` INT NULL,
    `nrSala` VARCHAR(10) NULL,
    `dia` DATE NULL,
    `hora` TIME NULL,
    INDEX `fk_turma_periodo1_idx` (`periodo_disciplina_idDisciplina` ASC , `periodo_curso_idCurso` ASC),
    PRIMARY KEY (`disciplina_idDisciplina`),
    CONSTRAINT `fk_turma_disciplina1` FOREIGN KEY (`disciplina_idDisciplina`)
        REFERENCES `mydb`.`disciplina` (`idDisciplina`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_turma_periodo1` FOREIGN KEY (`periodo_disciplina_idDisciplina` , `periodo_curso_idCurso`)
        REFERENCES `mydb`.`periodo` (`disciplina_idDisciplina` , `curso_idCurso`)
        ON DELETE NO ACTION ON UPDATE NO ACTION
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `mydb`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargo` (
  `idCargo` INT NOT NULL,
  `data_inicio` DATE NULL,
  `data_fim` DATE NULL,
  `cargo_nome` VARCHAR(45) NULL,
  `funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idCargo`, `funcionario_idFuncionario`),
  INDEX `fk_cargo_funcionario1_idx` (`funcionario_idFuncionario` ASC)  ,
  CONSTRAINT `fk_cargo_funcionario1`
    FOREIGN KEY (`funcionario_idFuncionario`)
    REFERENCES `mydb`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `matricula` INT NULL,
  `curso_idCurso` INT NOT NULL,
  `anoConclusaoEnsMed` YEAR(4) NULL,
  `escola2oGrau` VARCHAR(45) NULL,
  PRIMARY KEY (`matricula`, `curso_idCurso`),
  INDEX `fk_aluno_curso1_idx` (`curso_idCurso` ASC)  ,
  CONSTRAINT `fk_aluno_curso1`
    FOREIGN KEY (`curso_idCurso`)
    REFERENCES `mydb`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina_has_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina_has_curso` (
  `curso_idCurso` INT NULL,
  `disciplina_idDisciplina` INT NULL,
  PRIMARY KEY (`curso_idCurso`, `disciplina_idDisciplina`),
  INDEX `fk_curso_has_disciplina_disciplina1_idx` (`disciplina_idDisciplina` ASC)  ,
  INDEX `fk_curso_has_disciplina_curso1_idx` (`curso_idCurso` ASC)  ,
  CONSTRAINT `fk_curso_has_disciplina_curso1`
    FOREIGN KEY (`curso_idCurso`)
    REFERENCES `mydb`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_has_disciplina_disciplina1`
    FOREIGN KEY (`disciplina_idDisciplina`)
    REFERENCES `mydb`.`disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prerequisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prerequisito` (
  `disciplina_idDisciplina` INT NULL,
  `nomePrerequisito` VARCHAR(35) NULL,
  PRIMARY KEY (`disciplina_idDisciplina`),
  CONSTRAINT `fk_prerequisito_disciplina1`
    FOREIGN KEY (`disciplina_idDisciplina`)
    REFERENCES `mydb`.`disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
